jobs:
  log-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3

      - name: Log pull request to wiki
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ykb95/logging-pull-requests.wiki.git wiki
          cd wiki
          echo -e "## PR #1: Add GitHub Actions workflow\n- **Author**: ykb95\n- **Created At**: 2025-08-03T19:49:48Z\n- **State**: open\n- **Description**:\nnull" > "pr-1.md"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Add PR #1 to Wiki"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
